# Generated by Django 4.2 on 2024-05-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=600, unique=True)),
                ('model_no', models.CharField(max_length=200)),
                ('bill_detail', models.TextField(verbose_name='Text on Bill')),
                ('hsn_code', models.CharField(max_length=100, verbose_name='HSN / SAC Code')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TAX in %')),
                ('details', models.TextField()),
                ('specafications', models.TextField()),
                ('doc', models.DateTimeField(auto_now_add=True)),
                ('doe', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Visible')),
                ('category', models.ManyToManyField(to='product.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='media/product/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('doc', models.FileField(upload_to='media/product/docs/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
        ),
    ]
